### ISSUE TITLE
2D NRRD Support

### ISSUE THREAD

**Issue by MattTheCuber** [niivue/niivue-vscode#68]
Currently 2D NRRD does not load.

Here is an example scan from pynrrd: https://github.com/mhe/pynrrd/blob/master/nrrd/tests/data/test2d_ascii.nrrd

**Comment by korbinian90** [comment]
Thank you for reporting this!

The problem seems to be that the Niivue base library only supports the `raw` and `gz` encodings of NRRD. 
You can test this here, where it shows an error message: https://niivue.github.io/niivue/features/draganddrop.html
(I didn't figure out / have time yet to propagate error messages to vscode)

Here is the source code in Niivue, where the possible encodings are defined: https://github.com/niivue/niivue/blob/998281a283c1e1421be96c7c63ee2a96b37fc998/src/nvimage/index.ts#L2088

If you think this is important and should be fixed, you could ask for it in the main Niivue repository: https://github.com/niivue/niivue
